### ISSUE TITLE
v1.14.5 - v1.21.14 Kubernetes 跨版本升级记录

### ISSUE THREAD

**Issue by phosae** [phosae/phosae.github.io#32]
https://www.zeng.dev/post/2023-kubernetes-upgrade-1.14-1.21/?code=e81bc617d1311164cbc4

**Comment by pikez** [comment]
看了文章标题感觉和滴滴最近的事情很像呀哈哈

**Comment by phosae** [comment]
> @pikez
> 看了文章标题感觉和滴滴最近的事情很像呀哈哈

😂 网传的东西应该段子成分居多、当不得真

**Comment by phosae** [comment]
drain node 的好处在于，其可以搭配 PodDisruptionBudget (PDB) 保证应用 Pod 可用性

```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apigate
spec:
  maxUnavailable: 1 # 可以换成百分比
  selector:
    matchLabels:
      app: apigate
```

以上 PDB 配合 drain，可以保证 node 升级期间，网关应用只有 1 个实例受影响
